### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by albumns** [msmbuilder/msmbuilder#564]
Hello 

I am trying to run command:

```
msmb SolventApplyComponents --trjs ../md.xtc --top npt2.pdb --solvent_indices solvent.txt --solute_indices solute.txt --assignments waterassign --component tica_model.jl --out watercomponent
```

but it failed with messages:

```
An unexpected error has occurred with MSMBuilder (version 3.3.0.dev0.dev-Unknown), please
consider sending the following traceback to MSMBuilder GitHub issue tracker at:
            https://github.com/msmbuilder/msmbuilder/issues

Traceback (most recent call last):
  File "/usr/bin/msmb", line 9, in <module>
    load_entry_point('msmbuilder==3.3.0.dev0', 'console_scripts', 'msmb')()
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/cmdline.py", line 438, in start
    instance = klass(args)
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/cmdline.py", line 280, in __init__
    kwargs[k] = getattr(self, '_%s_type' % k)(v)
  File "/usr/lib64/python2.7/site-packages/WetMSM-0.3-py2.7-linux-x86_64.egg/wetmsm/vmd_write.py", line 303, in _component_type
    obj = utils.load(fn)
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/utils/io.py", line 65, in load
    "Joblib: {}".format(e1, e2)
IndexError: tuple index out of range
```

before this command, I've run the following successfully:

> msmb AtomIndices -p npt2.pdb -o solute.txt -a --alpha 
 >msmb AtomIndices -a -p npt2.pdb -o solvent.txt --water   

>msmb SolventShellsFeaturizer --trjs ../md.xtc --top npt2.pdb --solute_indices solute.txt --solvent_indices solvent.txt --n_shells 4 --shell_width 0.3 --out waterfeats

> msmb tICA -i waterfeats -t tica_transform -o tica_model.jl --n_components 5  

>  msmb SolventShellsAssigner --trjs ../md.xtc --top npt2.pdb --solvent_indices solvent.txt --solute_indices solute.txt --n_shells 4 --shell_width 0.3 --out waterassign

**Comment by mpharrigan** [comment]
It looks like it can't load `tica_model.jl`. Are you sure this is the filename?

Additionally, it looks like it's raising an exception while trying to print the error message which I'll look into

**Comment by albumns** [comment]
Thank you for reply.

I just noticed that after command line:

msmb tICA -i waterfeats -t tica_transform -o tica_model.jl --n_components 5

it didn't generate file  tica_model.jl , here is the log file for above command:

tICA(gamma=0.05, lag_time=1, n_components=5, weighted_transform=False)
Fitting model...
*********
*RESULTS*
*********
time-structure based Independent Components Analysis (tICA)
-----------------------------------------------------------
n_components        : 5
gamma               : 0.05
lag_time            : 1
weighted_transform  : False

Top 5 timescales :
[ 44.46292479  11.00509206   4.70818941   2.48589748   1.4415424 ]

Top 5 eigenvalues :
[ 0.97776038  0.91313913  0.80864451  0.66880068  0.49972296]

--------------------------------------------------------------------------------
Transforming 100%|###################################################################################|Time: 0:00:00

Saving transformed dataset to 'tica_transform.h5'
To load this dataset interactive inside an IPython
shell or notebook, run

  $ ipython
  >>> from msmbuilder.dataset import dataset
  >>> ds = dataset('tica_transform.h5')

Saving "tica_model.pkl"... (<class 'msmbuilder.decomposition.tica.tICA'>)
To load this tICA object interactively inside an IPython
shell or notebook, run: 

  $ ipython
  >>> from msmbuilder.utils import load
  >>> model = load('tica_model.pkl')


Do yo have any idea where is the  problem?

thx a lot

**Comment by mpharrigan** [comment]
Unfortunately this is a case where we're going to say "it's not a bug, it's a feature!" Msmbuilder automatically changes the file extension from `.jl` to `.pkl`. In the past, we used `joblib` to serialize objects. Now we are using python's `pickle` module.

I'll update the documentation to reflect the correct file extension. Sorry about that!

@rmcgibbo maybe we should only add an extension if the user doesn't provide one.

**Comment by albumns** [comment]
Hello,

Thank you for the kind explanations. I took the .pkl file and  try to run command:

msmb SolventApplyComponents --trjs md.xtc --top npt2.pdb --solvent_indices solvent.txt --solute_indices solute.txt --assignments waterassign --component tica_model.pkl --out watercomponent 

it failed with another messages:

ApplyComponents(agg_method=add,
        component=[ 0.39314  0.00723 ...,  0.0195   0.00097],
        solute_indices=['8' '15' ..., '5967' '5981'],
        solvent_indices=['6063' '6066' ..., '76617' '76620'], stride=1)
An unexpected error has occurred with MSMBuilder (version 3.3.0.dev0.dev-Unknown), please
consider sending the following traceback to MSMBuilder GitHub issue tracker at:
            https://github.com/msmbuilder/msmbuilder/issues

Traceback (most recent call last):
  File "/usr/bin/msmb", line 9, in <module>
    load_entry_point('msmbuilder==3.3.0.dev0', 'console_scripts', 'msmb')()
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/cmdline.py", line 440, in start
    instance.start()
  File "/usr/lib64/python2.7/site-packages/WetMSM-0.3-py2.7-linux-x86_64.egg/wetmsm/vmd_write.py", line 323, in start
    with dataset(self.assn, mode='r') as assn_dataset:
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/dataset.py", line 70, in dataset
    fmt = _guess_format(path)
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/dataset.py", line 117, in _guess_format
    if os.path.isdir(path):
  File "/usr/lib64/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, argument found

**Comment by albumns** [comment]
could somebody give some comments on the new errors?

Thanks a lot

@mpharrigan
@rmcgibbo

**Comment by mpharrigan** [comment]
Sorry for not investigating this sooner. This is a bug, fixed in PR mpharrigan/wetmsm#11

**Comment by albumns** [comment]
thank you for the reply. 

What I should do to fix this bug? download the latest version of msmb and rebuild it again?

thanks

@mpharrigan

**Comment by rmcgibbo** [comment]
The bug was in the wetmsm plugin, so the thing to do is to download and reinstall the latest version of https://github.com/mpharrigan/wetmsm

**Comment by albumns** [comment]
Hello,

thanks a lot for debugging. The command is still failed, but with different errors:


1/msmb> msmb SolventApplyComponents --trjs md.xtc --top npt2.pdb --solvent_indices solvent.txt --solute_indices solute.txt --assignments waterassign --component tica_model.pkl --out watercomponent 


ApplyComponents(agg_method=add,
        component=[ 0.39314  0.00723 ...,  0.0195   0.00097],
        solute_indices=['8' '15' ..., '5967' '5981'],
        solvent_indices=['6063' '6066' ..., '76617' '76620'], stride=1)
/usr/lib64/python2.7/site-packages/WetMSM-0.3-py2.7-linux-x86_64.egg/wetmsm/vmd_write.py:173: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  user = np.zeros((ceil(traj.n_frames / self.stride), traj.n_atoms))
An unexpected error has occurred with MSMBuilder (version 3.3.0.dev0.dev-Unknown), please
consider sending the following traceback to MSMBuilder GitHub issue tracker at:
            https://github.com/msmbuilder/msmbuilder/issues

Traceback (most recent call last):
  File "/usr/bin/msmb", line 9, in <module>
    load_entry_point('msmbuilder==3.3.0.dev0', 'console_scripts', 'msmb')()
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/cmdline.py", line 440, in start
    instance.start()
  File "/usr/lib64/python2.7/site-packages/WetMSM-0.3-py2.7-linux-x86_64.egg/wetmsm/vmd_write.py", line 331, in start
    (traj_dataset[tr_key], assn_dataset[as_key])
  File "/usr/lib64/python2.7/site-packages/WetMSM-0.3-py2.7-linux-x86_64.egg/wetmsm/vmd_write.py", line 194, in partial_transform
    self.stride)
  File "wetmsm/_vmd_write.pyx", line 56, in wetmsm._vmd_write._compute_chunk_add (wetmsm/_vmd_write.c:2098)
ValueError: Buffer dtype mismatch, expected 'long' but got Python object

@mpharrigan
@rmcgibbo
